# Generated by Django 4.1.1 on 2022-09-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('personal_identification', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=254)),
                ('country', models.CharField(max_length=254)),
                ('organization', models.CharField(max_length=254)),
                ('sector', models.CharField(choices=[('University', 'university'), ('Politics', 'politics'), ('Union', 'union')], max_length=30)),
                ('organization_email', models.EmailField(max_length=254)),
                ('organization_phone', models.CharField(max_length=254)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
