# Generated by Django 4.1.1 on 2022-09-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0002_alter_organizer_options_organizer_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='status',
            field=models.BooleanField(default=False, verbose_name='accepted as organizer'),
        ),
    ]
