# Generated by Django 4.1.1 on 2022-09-28 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0003_alter_organizer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='organization_position',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
