# Generated by Django 4.1.1 on 2022-09-30 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0004_organizer_organization_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='id_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizer',
            name='sector',
            field=models.CharField(max_length=30),
        ),
    ]
